### ISSUE TITLE
Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.

### ISSUE THREAD

**Issue by Yash-Kavaiya** [sudarshan-koirala/llama2-chat-with-documents#3]
Is these any other way to solve this  error (like create docker container and run it )
Traceback (most recent call last):
  File "/workspaces/langchain-car-chatbot/llama2-chat-with-documents/ingest.py", line 62, in <module>
    create_vector_database()
  File "/workspaces/langchain-car-chatbot/llama2-chat-with-documents/ingest.py", line 52, in create_vector_database
    vector_database = Chroma.from_documents(
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 646, in from_documents
    return cls.from_texts(
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 601, in from_texts
    chroma_collection = cls(
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 80, in __init__
    import chromadb
  File "/home/codespace/.python/current/lib/python3.10/site-packages/chromadb/__init__.py", line 77, in <module>
    raise RuntimeError(

**Comment by sudarshan-koirala** [comment]
hello, you need to update the python version, try using python version 3.11
